# Default values for helm-scale-test.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

env:
  CPU: 1
  TIME: 2m
  SLEEP: 2m

replicaCount: 1

image:
  repository: debian
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "stable-slim"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
   cpu: 1
   memory: 64Mi
  requests:
   cpu: 500m
   memory: 32Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 4
#  targetCPUUtilizationPercentage: 5000m
  external: 999m




